name: Loyola Automatic Watcher

on:
  push:
  schedule:
      - cron: "0,30 * * * *"
      # 毎時00分・30分に起動
      # 夜間は実行しなくてもいい気はするが、念の為昼夜問わず実行するようにしておく

jobs:
  Watcher:
    runs-on: ubuntu-latest

    env:
      LOYOLA_ID: ${{ secrets.LOYOLA_ID }}
      LOYOLA_PASSWORD: ${{ secrets.LOYOLA_PASSWORD }}
      LOYOLA_URI: ${{ secrets.LOYOLA_URI }}
      DISCORD_WEBHOOK_URL_OF_ADMIN_SERVER: ${{ secrets.DISCORD_WEBHOOK_URL_OF_ADMIN_SERVER }}
      DISCORD_WEBHOOK_URL_OF_PUBLIC_SERVER: ${{ secrets.DISCORD_WEBHOOK_URL_OF_PUBLIC_SERVER }}

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        cache: 'yarn'
    
    - name: Install dependencies
      run: yarn install

    - name: Create dotenv file
      shell: bash
      working-directory: ./settings
      run: touch .env | 
        echo "LOYOLA_ID=${{ secrets.LOYOLA_ID }}" >> .env
        echo "LOYOLA_PASSWORD=${{ secrets.LOYOLA_PASSWORD }}" >> .env
        echo "LOYOLA_URI=${{ secrets.LOYOLA_URI }}" >> .env
        echo "DISCORD_WEBHOOK_URL_OF_ADMIN_SERVER=${{ secrets.DISCORD_WEBHOOK_URL_OF_ADMIN_SERVER }}" >> .env
        echo "DISCORD_WEBHOOK_URL_OF_PUBLIC_SERVER=${{ secrets.DISCORD_WEBHOOK_URL_OF_PUBLIC_SERVER }}" >> .env

    - name: Install required packages to run (ex. Japanese fonts)
      run: sudo apt-get update && sudo apt-get install -y xvfb fonts-noto
      # 文字化けを防ぐ生活の知恵
      # https://qiita.com/zyyx-matsushita/items/c33f79e33f242395019e

    - name: Watch Loyola
      shell: bash
      env:
        LANG: "ja_JP.UTF-8"
      run: xvfb-run --auto-servernum --server-args='-screen 0, 1600x900x24' node ./index.js
      # headless: falseで動かすための生活の知恵
      # https://github.com/peterdanis/electron-puppeteer-demo/issues/171

    - name: Set the current datetime
      env:
        TZ: 'Asia/Tokyo'
      run: echo "CURRENT_DATETIME=$(date --iso-8601=minutes)" >> $GITHUB_ENV
    
    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with: 
        commit_message: 'updated: ${{ env.CURRENT_DATETIME }}'
        branch: master
